development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pedplus_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pedplus_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  database: pedplus_production
  username: pedplus
  password: d4qeQs4mjafcx88N
  timeout: 5000
