development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pedplus_development2
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pedplus_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
