org = Organization.create(:name => 'Sample Organization',
                            :slug => 'Sample',
                            :country => "United States",
                            :owns_pedcount => true,
                            :owns_pedplus => false,
                            :time_zone => 'Pacific Time (US & Canada)',
                            :default_max_number_of_gates_per_project => 1000,
                            :subscription_active_until => Date.today + 1.year,
                            :default_counting_days_per_gate => 4,
                            :extra_counting_day_credits_available => 1000,
                            :allowed_to_export_projects => true,
                            :kind => 'professional')
                            
user = User.create(:first_name => 'Sample',
                   :last_name => 'User',
                   :email => 'user@sample.com',
                   :password => 'changeme',
                   :password_confirmation => 'changeme',
                   :organization => org,
                   :organization_manager => true,
                   :organization_billing => true,
                   :s3sol_admin => true)
